Update convert-xml-to-markdown.yml

diff --git a/.github/workflows/convert-xml-to-markdown.yml b/.github/workflows/convert-xml-to-markdown.yml
--- a/.github/workflows/convert-xml-to-markdown.yml
+++ b/.github/workflows/convert-xml-to-markdown.yml
@@ -1,5 +1,4 @@
 name: Convert XML to Markdown
-
 on:
   push:
     branches:
@@ -14,17 +13,18 @@ jobs:
   convert:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3.5.0
+      - name: Checkout source repository
+        uses: actions/checkout@v4
 
-      - name: Set up JDK 11
-        uses: actions/setup-java@v3.5.0
+      - name: Set up JDK
+        uses: actions/setup-java@v4
         with:
           java-version: '11'
           distribution: 'temurin'
+          cache: 'maven'
 
       - name: Checkout DocusaurusWebsite repository
-        uses: actions/checkout@v3.5.0
+        uses: actions/checkout@v4
         with:
           repository: Pantagrueliste/CavrianaCorr_FrontEnd
           path: CavrianaCorr_FrontEnd
@@ -32,21 +32,32 @@ jobs:
 
       - name: Download Saxon
         run: |
-          wget -O saxon.jar https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/10.6/Saxon-HE-10.6.jar
+          wget -O saxon.jar https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/12.3/Saxon-HE-12.3.jar
+
+      - name: Create docs directory if it doesn't exist
+        run: |
+          mkdir -p CavrianaCorr_FrontEnd/docs
 
       - name: Convert XML to Markdown
         run: |
           for file in ./letters/*.xml; do
-            filename=$(basename -- "$file")
-            output_file="CavrianaCorr_FrontEnd/docs/${filename%.*}.md"
-            java -jar saxon.jar -s:"$file" -xsl:transform.xsl -o:"$output_file"
+            if [ -f "$file" ]; then
+              filename=$(basename -- "$file")
+              output_file="CavrianaCorr_FrontEnd/docs/${filename%.*}.md"
+              echo "Converting $file to $output_file"
+              java -jar saxon.jar -s:"$file" -xsl:transform.xsl -o:"$output_file"
+              if [ $? -ne 0 ]; then
+                echo "Error converting $file"
+                exit 1
+              fi
+            fi
           done
 
       - name: Commit and push changes
         run: |
           cd CavrianaCorr_FrontEnd
-          git config --local user.email "action@github.com"
-          git config --local user.name "GitHub Action"
-          git add docs
-          git commit -m "Convert XML to Markdown" || echo "No changes to commit"
+          git config --local user.email "github-actions[bot]@users.noreply.github.com"
+          git config --local user.name "github-actions[bot]"
+          git add docs/
+          git diff --cached --quiet || git commit -m "Update converted Markdown files"
           git push origin main
